// TiendaGuitarrasVue/TiendaGuitarras/src/components/Header.vue
<script setup>
import Guitarra from './Guitarra.vue';
import { computed } from 'vue';


    const emit = defineEmits(['reducir-cantidad', 'aumentar-cantidad', 'borrar-guitarra', 'borrar-carrito', 'agregar-carrito'])

    const props = defineProps({
        carrito: {
            type: Object,
            required: true
        },
        guitarra: {
            type: Object,
            required: true
        },
        precio: {
            type: Number,
            required: true
        }
    })

    const precioTotal = computed(() => {
        return props.carrito.reduce((total, element) => total + (element.cantidad * element.precio), 0)
    });

</script>

<template>
    <header class="py-5 header">
        <div class="container-xl">
            <div class="row justify-content-center justify-content-md-between">
                <div class="col-8 col-md-3">
                    <a href="index.html">
                        <img class="img-fluid" src="/img/logo.svg" alt="imagen logo">
                    </a>
                </div>
                <nav class="col-md-6 a mt-5 d-flex align-items-start justify-content-end">
                    <div 
                        class="carrito"
                    >
                        <img class="img-fluid" src="/img/carrito.png" alt="imagen carrito" />

                        <div id="carrito" class="bg-white p-3">
                            <p v-if="carrito.length === 0" class="text-center m-0">El carrito esta vacio</p>
                            <div v-else>
                                <table class="w-100 table">
                                    <thead>
                                        <tr>
                                            <th>Imagen</th>
                                            <th>Nombre</th>
                                            <th>Precio</th>
                                            <th>Cantidad</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr v-for="producto in carrito">
                                            <td>
                                                <img class="img-fluid" 
                                                v-bind:src="`/img/${producto.imagen}.jpg`" alt="imagen guitarra">
                                            </td>
                                            <td>{{ producto.nombre }}</td>
                                            <td class="fw-bold">
                                                    {{ producto.precio }}€
                                            </td>
                                            <td class="flex align-items-start gap-4">
                                                <button
                                                    type="button"
                                                    class="btn btn-dark"
                                                    @:click="$emit('cambiar-cantidad',producto, 0)"
                                                >
                                                    -
                                                </button>
                                                    {{ producto.cantidad }}
                                                <button
                                                    type="button"
                                                    class="btn btn-dark"
                                                    @:click="$emit('cambiar-cantidad',producto, 1)"
                                                >
                                                    +
                                                </button>
                                            </td>
                                            <td>
                                                <button
                                                    class="btn btn-danger"
                                                    type="button"
                                                    @:click="$emit('borrar-guitarra',producto)"
                                                >
                                                    X
                                                </button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <p class="text-end">Total pagar: <span class="fw-bold">{{ precioTotal }}€</span></p>
                                <button class="btn btn-dark w-100 mt-3 p-2" 
                                @:click="$emit('borrar-carrito')">
                                Vaciar Carrito
                                </button>
                            </div>
                        </div>
                    </div>
                </nav>
            </div><!--.row-->

            <div class="row mt-5">
                <div class="col-md-6 text-center text-md-start pt-5">
                    <h1 class="display-2 fw-bold">{{ guitarra.nombre }}</h1>
                    <p class="mt-5 fs-5 text-white">{{ guitarra.descripcion }}</p>
                    <p class="text-primary fs-1 fw-black">{{ guitarra.precio }}€</p>
                    <button 
                        type="button"
                        class="btn fs-4 bg-primary text-white py-2 px-5"
                        @:click="$emit('agregar-carrito',guitarra)"
                    >Agregar al Carrito</button>
                </div>
            </div>
        </div>

        <img class="header-guitarra" src="/img/header_guitarra.png" alt="imagen header">
    </header>
</template>

<style lang="scss" scoped>

</style>

// devTiendaGuitarra/tiendaGuitarra/src/components/Header.jsx
import { useMemo } from "react";

export default function Header({carrito, eliminarDelCarrito, cambiarCantidad, eliminarCarrito}) {

    const carritoVacio = useMemo(() => carrito.length === 0, [carrito]);
    const carritoTotal = useMemo(() => carrito.reduce((total, element) => total + (element.cantidad * element.price), 0),[carrito]);

    return(
        <>
            <header className="py-5 header">
                <div className="container-xl">
                    <div className="row justify-content-center justify-content-md-between">
                        <div className="col-8 col-md-3">
                            <a href="index.html">
                                <img className="img-fluid" src="img/logo.svg" alt="imagen logo" />
                            </a>
                        </div>
                        <nav className="col-md-6 a mt-5 d-flex align-items-start justify-content-end">
                            <div 
                                className="carrito"
                            >
                                <img className="img-fluid" src="img/carrito.png" alt="imagen carrito" />

                                <div id="carrito" className="bg-white p-3">
                                    {carritoVacio ? (
                                    <p className="text-center">El carrito esta vacio</p>
                                    )
                                    : 
                                    (
                                        <table className="w-100 table">
                                            <thead>
                                                <tr>
                                                    <th>Imagen</th>
                                                    <th>Nombre</th>
                                                    <th>Precio</th>
                                                    <th>Cantidad</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {carrito.map(element =>
                                                <tr key={element.id}>
                                                    <td>
                                                        <img className="img-fluid" src={`img/${element.image}.jpg`} alt="imagen guitarra" />
                                                    </td>
                                                    <td>{element.name}</td>
                                                    <td className="fw-bold">
                                                            {element.price}€
                                                    </td>
                                                    <td className="flex align-items-start gap-4">
                                                        <button
                                                            type="button"
                                                            className="btn btn-dark"
                                                            onClick={() =>cambiarCantidad(element.id, 0)}
                                                        >
                                                            -
                                                        </button>
                                                            {element.cantidad}
                                                        <button
                                                            type="button"
                                                            className="btn btn-dark"
                                                            onClick={() =>cambiarCantidad(element.id, 1)}
                                                        >
                                                            +
                                                        </button>
                                                    </td>
                                                    <td>
                                                        <button
                                                            className="btn btn-danger"
                                                            type="button"
                                                            onClick={() => eliminarDelCarrito(element.id)}
                                                        >
                                                            X
                                                        </button>
                                                    </td>
                                                </tr>)}
                                            </tbody>
                                        </table>
                                    )
                                    }
                                    <p className="text-end">Total pagar: <span className="fw-bold">{carritoTotal}€</span></p>
                                    <button className="btn btn-dark w-100 mt-3 p-2" onClick={() =>eliminarCarrito()}>Vaciar Carrito</button>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </header>
        </>
    )
}
